### ISSUE TITLE
change cost estimator for replication

### ISSUE THREAD

**Issue by rolph-recto** [apl-cornell/viaduct#119]
The cost estimator should minimize the number of hosts storing a variable; this should be offset by greater cost of remote communication induced by *not* replicating a variable.

e.g. The cost estimator should (1) store a variable in `Local(A)`, unless (2) both `A` and `B` access it, in which case it should be stored in `Replication(A,B)`. The current implementation of the estimator enforces (2) by inducing cost for remote communication, but does not enforce (1) because the storage cost of `Local(A)` and `Replication(A,B)` are the same.

**Comment by cacay** [comment]
Resolved by #200.
