### ISSUE TITLE
Replication protocol should check for equivocation

### ISSUE THREAD

**Issue by rolph-recto** [apl-cornell/viaduct#120]
If A and B receive a cleartext value from C, A and B should check if they received the same value.

**Comment by ianwilkietomasik** [comment]
Chuck hangs in this program:

`host chuck : {((A & B) & C)}

host alice : {((A & B) & C)}

host bob : {((A & B) & C)}

process main {
    let $tmp@Local(host = chuck) = input int from chuck;
    let $tmp2@Replication(hosts = {alice, chuck}) = $tmp;
    val n: int@Replication(hosts = {alice, bob}) = $tmp2;
    var prod: int@Local(host = alice) = 1;
    var i: int@Replication(hosts = {alice, bob}) = 0;
    loop {
        let $tmp_1@Replication(hosts = {alice, bob}) = i;
        let $tmp_2@Replication(hosts = {alice, bob}) = n;
        let $tmp_3@Replication(hosts = {alice, bob}) = ($tmp_1 < $tmp_2);
        if ($tmp_3) {
            let $tmp_4@Local(host = alice) = input int from alice;
            val a: int@Local(host = alice) = $tmp_4;
            let $tmp_5@Local(host = bob) = input int from bob;
            val b: int@Local(host = alice) = $tmp_5;
            let $tmp_6@Local(host = alice) = prod;
            let $tmp_7@Local(host = alice) = a;
            let $tmp_8@Local(host = alice) = b;
            let $tmp_9@Local(host = alice) = ($tmp_7 * $tmp_8);
            let $tmp_10@Local(host = alice) = ($tmp_6 + $tmp_9);
            prod = $tmp_10;
            i += 1;
        } else {
            break;
        }
    }
    let $tmp_11@Local(host = alice) = prod;
    output $tmp_11 to alice;
    let $tmp_12@Local(host = alice) = prod;
    output $tmp_12 to bob;
}
`
