### ISSUE TITLE
add type expressions

### ISSUE THREAD

**Issue by rolph-recto** [apl-cornell/viaduct#18]
The surface language currently doesn't have a way of specifying the type of a variable during declaration, only its security label. We should have a type grammar for specifying valid type expressions to be used for variable declaration.

example with arrays:

```
PRETYPE = int | bool | TYPE []
TYPE = PRETYPE LABEL
```

**Comment by cacay** [comment]
Resolved by 47bf9290eeb4df70fb526af2676f911f03271752.
