### ISSUE TITLE
Intern labels and memoize label operations

### ISSUE THREAD

**Issue by cacay** [apl-cornell/viaduct#41]
Security labels are implemented as sets of sets, so operations like `flowsTo`, `meet`, and `join` are quite expensive. Label inference and protocol selection call these repeatedly, and protocol selection is slow. One way to make protocol selection faster is by optimizing these operations.

An easy fix would be to memoize these operations. Unfortunately, `equals` and `hashCode` on `Set<Set<*>>` are slow enough that this may not be an improvement. [HashConsing](https://en.wikipedia.org/wiki/Hash_consing) labels so that there is only ever one instance of each unique label would make these operations constant time (since we can now use object identity), significantly improving the effectiveness of memoization.

We should, of course, profile before jumping the shark.

Some resources regarding memoization and interning:
- [funKTionale](https://github.com/MarioAriasC/funKTionale/blob/master/funktionale-memoization/src/main/kotlin/org/funktionale/memoization/namespace.kt) (semi deprecated, to be superseded by [Λrrow](https://github.com/arrow-kt/arrow))
- [MnemoniK](https://github.com/aballano/mnemonik)
- [This blog post](https://jorgecastillo.dev/kotlin-purity-and-function-memoization)

**Comment by andrewcmyers** [comment]
Visual vm is an easy way to get profiles

**Comment by cacay** [comment]
https://visualvm.github.io/

**Comment by andrewcmyers** [comment]
I think it's in the standard Java distribution

**Comment by cacay** [comment]
Label operations are not a significant contributor to compile time. For example, label inference takes up only a small portion of total compilation time. Main bottleneck is protocol selection, which solves (a rather unoptimized) ILP problem.

**Comment by andrewcmyers** [comment]
Cost of label operations is not a big deal for Viaduct. It is a big issue for systems like Jif, Fabric,  and SCIF, for what it's worth, because it happens at run time.  @s-ren
