### ISSUE TITLE
enforce ordering b/w IO and downgrading by synchronization

### ISSUE THREAD

**Issue by rolph-recto** [apl-cornell/viaduct#96]
currently only ordering between downgrades is preserved by synchronization; need to preserve ordering b/w IO and downgrading as well. for example, consider

```
val a = endorse (input from alice)
val a2 = declassify a
val b = input from bob 
```

only the ordering for `a` and `a2` will be preserved; the runtime can allow execution of `b` before `a2`, which might be insecure in some cases

**Comment by cacay** [comment]
Reordering IO wrt to downgrades is safe because security behavior is only affected by downgrades.
